FROM node:18 AS build
WORKDIR /app
COPY package*.json .
RUN npm instal
COPY . .
RUN npm run build

FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
COPY --from=build /app/dist/nome-do-app /usr/share/nginx/html
